[package]
name = "rustdoc-viewer"
version = "0.1.1"
edition = "2024"
description = "A terminal-based viewer for Rust documentation."
keywords = ["rustdoc", "terminal", "viewer"]
categories = ["command-line-utilities", "development-tools"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/abusch/rustdoc-viewer"
readme = "README.md"

[[bin]]
name = "rdv"
path = "src/main.rs"

[dependencies]
anyhow = "1"
arborium = { version = "2.18.1", features = ["lang-rust"] }
arborium-highlight = "2.18.1"
arborium-theme = "2.18.1"
frizbee = "0.13"
opaline = { version = "0.4.2", features = ["global-state"] }
pulldown-cmark = { version = "0.13", default-features = false }
ratatui = "0.30"
rustdoc-types = "0.61"
serde_json = "1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
